### ISSUE TITLE
Nothing received

### ISSUE THREAD

**Issue by martenumberto** [SpaceTeddy/CC1101#10]
Hi,

im running your RX_Demo on a Raspberry as following:

> sudo ./RX_Demo -f 868 -v

Some Stuff is Running on that Frequency but nothing will be received. The last Output is "PaTable: 0x03 0x17...". Whats wrong?

**Comment by SpaceTeddy** [comment]
Which parameters did you use for the TX_Demo program?

**Comment by SpaceTeddy** [comment]
does it work?
