### ISSUE TITLE
SPI1 not supported?

### ISSUE THREAD

**Issue by salmg** [SpaceTeddy/CC1101#14]
Hello there,

Amazing work with this project.

I was trying to use your library with SPI1 instead of SPI0

![image](https://user-images.githubusercontent.com/7434935/29506840-70384f96-8602-11e7-942c-839dbd46f1de.png)

I made the next changes in the files:

- I added the dtoverlay=spi1-3cs at /boot/config.txt
- I changed the #define SS_PIN   10 in cc1100_raspi.h to 27(which corresponds to the GPIO 16 in the WiringPi pinout).
- Also I changed the wiringPiSPISetup in the cc1100_raspi.cpp file for the "1" instead of the "0" channel and same changes in the wiringPiSPIDataRW method, but I got nothing:

$ sudo ./TX_Demo -v -a1 -r0 -i1000 -t5 -c1 -f315 -m100
CC1100 SW: Verbose option is set `'
Raspberry CC1101 SPI Library test
Init CC1100...
Version: 0x00
no CC11xx found!

any ideas?

**Comment by SpaceTeddy** [comment]
Hi salmg,

I didn't tried to change the SPI channel, but this CC1101 library uses wiringPi for the raspberryPi SPI communication. Please check the SPI documentation here: http://wiringpi.com/reference/spi-library/

Please modify the following functions to SPI channel 1 in the cc1100_raspi.cpp file:
- wiringPiSPISetup (0, ...) -> wiringPiSPISetup (1, ...)
- wiringPiSPIDataRW (0,...) -> wiringPiSPIDataRW (1,...)

I did not tested it, but please try it.

**Comment by salmg** [comment]
Hello,

I tried different things but none worked.

So I decided to try the second SPI device as slave with this configuracion:
![image](https://user-images.githubusercontent.com/7434935/29548476-0cb5d2cc-86b6-11e7-9a7b-600c51e912b7.png)

It is working now with two projects sharing the same SPI0. Thanks.

**Comment by SpaceTeddy** [comment]
Yes, this is the simplest solution if your speed requirements for two devices are ok.

**Comment by salmg** [comment]
that's true! do you have an email where I can contact you?

**Comment by SpaceTeddy** [comment]
spaceteddy1@gmx.net
