### ISSUE TITLE
Trying to receive signal from CCdebugger and smartRF studio

### ISSUE THREAD

**Issue by Bob1237** [SpaceTeddy/CC1101#16]
Hello

FIrst let me tell you i am a complete noob to raspberry and cc1101 , so i don't know a lot about it.
But i was wondering if it was possible to use your code to receive a signal with the raspberry pi and cc1101 send by smart RF studio and the ccdebugger. Because I have followed your readme file and did everthing like you said , but i don't receive anything , and  i am using the same frequentcy , modulation ,... 
My problem is similar to the one were you talk about inthe issues: Not Receiving Anything #11
but nothing he did there works for me.

if you know anything about this let me know

Thanks 

BoB1237

**Comment by SpaceTeddy** [comment]
Hi Bob, 
thanks to try my library. 

May you please post some terminal  output logs of the RX_Demo and TX_Demo? In addition, detailed pictures of your hardware Setup are helpful!

Thank you,

Kind regards,
Chris

**Comment by Bob1237** [comment]
hello

this is my terminal output : 
![image](https://user-images.githubusercontent.com/34129030/33714391-10b96e86-db4f-11e7-81f6-7d1d7d58022f.png)

and here are picture of the connection but i don't think there something wrong whith that because i connect it exactly the same like you. (sorry for the bad picture) 
![image](https://user-images.githubusercontent.com/34129030/33714466-4fdfd564-db4f-11e7-91b0-5ada8728fcc1.png)
![image](https://user-images.githubusercontent.com/34129030/33714488-685b5000-db4f-11e7-9d8d-1685eb894128.png)
![image](https://user-images.githubusercontent.com/34129030/33714510-790d76bc-db4f-11e7-82fd-67dfb25bc1d2.png)

first one is from the transmitting end

Sorry for the late rasponds

Bob

**Comment by SpaceTeddy** [comment]
Dear Bob,

your register settings looks not correct and you used non valid command line parameters.
May you please follow the example command line parameters?
try: 
sudo ./RX_Demo -v -a3 -c1 -f434 -m100 (receiver address 3; channel 1; frequency 434; modulation 100kbit GMSK)

I've never used this CCdebugger. Unfortunatly I can not help you.

**Comment by SpaceTeddy** [comment]
did you try again to keep it running?
