### ISSUE TITLE
Will the TX_Demo and RX_Demo work on one raspberry pi at the same time?

### ISSUE THREAD

**Issue by ole1986** [SpaceTeddy/CC1101#36]
While I am struggling to get a signal I was asking myself if its even possible to use both commands, the TX_Demo and RX_Demo at the same time on a single raspberry pi (v1 Mod B+)

The only thing I am sometimes receiving on RX_Demo side is: 
`no bytes in RX buffer or RX Overflow!: 0x00`

Thank you in advanced for any response

**Comment by SpaceTeddy** [comment]
well, as I remember right, the PI has two SPI chip select pins, means you can theoretically use two SPI devices with one pi. But I guess in reality it needs effort do write a driver, which checks that the bus is free. If you want to transfer many bytes, you have to take care about the timings, therefore I guess that it is more effective to setup a second rPi.

**Comment by ole1986** [comment]
@SpaceTeddy thank you for your answer. Highly appreciated
