### ISSUE TITLE
cc1101.h missing

### ISSUE THREAD

**Issue by mrfaptastic** [SpaceTeddy/CC1101#4]
Hi, could you please commit cc1101.h such that this can be compiled?

**Comment by SpaceTeddy** [comment]
hi,
to make it more easy for you, I changed it for a non LIB version.
Just copy the RX_Demo or TX_demo to the arduino Editor and load the cc1100_arduino.cpp and cc1100_arduino.h to your sketch. 
I tested it and it compiles well.

try again.

chris

**Comment by mrfaptastic** [comment]
Thank you! I will test.

**Comment by SpaceTeddy** [comment]
files updated
