### ISSUE TITLE
TX-only without addressing 

### ISSUE THREAD

**Issue by ugurturkel** [SpaceTeddy/CC1101#40]
Hey,
I want to use this library for transmitting more than thousand bytes as 61 bytes packets. And since I'm just going to decode the signal with RTL-SDR, How can I use CC1101 for just transmitting on the air without any addressing? 

Thank you.

**Comment by SpaceTeddy** [comment]
well, long time ago, that I have worked with this type of controller and basically it was on my to-do list to implement a non-address mode, or called synchronous mode, but I have no time for that unfortunately. Probably you can get some impulses [here](https://github.com/RFD-FHEM/SIGNALDuino) to implement this in your library.
