### ISSUE TITLE
How hard to receive ademco door sensors?

### ISSUE THREAD

**Issue by esdad697** [SpaceTeddy/CC1101#6]
The sensor uses 345Mhz, OOK modulation.

Looks like CC1100::set_ISM(uint8_t ism_freq) sets the frequency. How are frequency's set? 
					freq2=0x0C;
					freq1=0x1D;
					freq0=0x89;
					spi_write_burst(PATABLE_BURST,patable_power_315,8);

**Comment by SpaceTeddy** [comment]
in this demo, you can not set a specific frequency. You can set a frequency range like 315, 433, 868 or 915 MHz and a channel number. If you like a specific frequency you may can try to uncomment the void CC1100::set_freq(uint32_t freq). but I haven't tested it.
