### ISSUE TITLE
Wiring?

### ISSUE THREAD

**Issue by Ken98045** [SpaceTeddy/CC1101#7]
Could you clarify the wiring setup you are using?  I think I understand it, but since I'm just getting started with the 1101 it is somewhat unclear since there appear to be some options.  Just a note in the readme or in a source comment would be very helpful.  Maybe I just missed it, but....

Also, a transmit example for the pi to go with the receive  example would be helpful too.

Thanks!

**Comment by SpaceTeddy** [comment]
Hi Ken,
I have updated the readme with a pinout for this demo. 
I take a look for a TX demo for the Raspi, but the main loop should be very similar to the Arduino TX demo.
regards,
Chris

**Comment by Ken98045** [comment]
Thanks!

**Comment by SpaceTeddy** [comment]
I created also an TX_Demo for Raspi.
Unfortunately I can not test it.
